import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Client wrapper component could be better but sticking to direct edit if possible. 
// Wait, Layout is Server Component by default in Next.js App Router (metadata export present).
// I cannot use hooks directly in RootLayout. 
// I need to create a Client Component for the banner or make Layout a client component (bad for metadata).
// I will create a `ShopStatusBanner` component and import it.

import { ShopStatusBanner } from "@/components/layout/ShopStatusBanner";
import { AnnouncementBanner } from "@/components/layout/AnnouncementBanner";

import { SHOP_CONFIG } from "@/data";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeStyles = {
    '--primary': SHOP_CONFIG.theme.primary,
    '--background': SHOP_CONFIG.theme.background,
  } as React.CSSProperties;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-transparent min-h-screen relative`}
        style={themeStyles}
      >
        {/* GLOBAL BACKGROUND - CRYSTAL UI */}
        {(() => {
          const bgConfig = SHOP_CONFIG.theme.backgroundImage;
          if (!bgConfig) return null;

          const isHex = bgConfig.trim().startsWith('#');

          if (isHex) {
            return (
              <div
                className="fixed inset-0 z-[-1]"
                style={{ backgroundColor: bgConfig }}
              />
            );
          }

          return (
            <div
              className="fixed inset-0 z-[-1] bg-cover bg-center bg-no-repeat bg-fixed"
              style={{ backgroundImage: `url(${bgConfig})` }}
            />
          );
        })()}
        {/* CONTRAST SHIELD - CRYSTAL UI */}
        <div className="fixed inset-0 z-[-1] bg-black/60 pointer-events-none" />

        <AnnouncementBanner />
        <ShopStatusBanner />

        {/* Content Wrapper - Full Width */}
        <div className="w-full min-h-screen bg-transparent shadow-none transition-all relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
